[package]
name = "jbig2dec"
version = "0.1.4"
authors = ["messense <messense@icloud.com>"]
description = "Rust binding to jbig2dec"
license = "GPL-3.0"
edition = "2018"
keywords = ["image", "pdf", "jbig2", "jb2"]
repository = "https://github.com/messense/jbig2dec-rs"
readme = "README.md"

[dependencies]
jbig2dec-sys = { version = "0.1", path = "jbig2dec-sys" }
image = { version = "0.23", default-features = false, features = ["png"], optional = true }
png = "0.15.3"

[dev-dependencies]
image = "0.23"

[features]
default = ["with-image"]
with-image = ["image"]

[workspace]
members = [
    ".",
    "jbig2dec-sys"
]
