[package]
name = "jbig2dec"
version = "0.1.1"
authors = ["messense <messense@icloud.com>"]
description = "Rust binding to jbig2dec"
license = "GPL-3.0"
edition = "2018"
keywords = ["image", "pdf", "jbig2", "jb2"]
repository = "https://github.com/messense/jbig2dec-rs"
readme = "README.md"

[dependencies]
jbig2dec-sys = { version = "0.1.0", path = "jbig2dec-sys" }

[workspace]
members = [
    ".",
    "jbig2dec-sys"
]
